name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Pull new changes
        run: git -C /home/bank-site pull
      - name: Stop old container
        run: docker rm $(docker stop $(docker ps -a -q --filter ancestor=bank-site --format="{{.ID}}"))
      - name: Delete old image
        run: docker rmi bank-site
      - name: Build new image
        run: docker build /home/bank-site -t "bank-site"
      - name: Run new container
        run: docker run -d -p 8081:8081 bank-site
