name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stop old container
        run: docker rm $(docker stop $(docker ps -a -q --filter ancestor=bank-site --format="{{.ID}}"))
      - name: Build new image
        run: docker build /home/bank-site -t "bank-site"
      - name: Run new image
        run: docker run -d -p 8081:8081 bank-site
